import { APP_PREFIX_PATH, UI_COMPONENTS_PREFIX_PATH } from 'constants/route.constant'
import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_COLLAPSE,
    NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant'
import { ADMIN, USER } from 'constants/roles.constant'

const uiComponentNavigationConfig = [
    // {
    //     key: 'uiComponent',
    //     path: '',
    //     title: 'Ui Component',
    //     translateKey: 'nav.uiComponents',
    //     icon: 'uiComponents',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [ADMIN],
    //     subMenu: [
    //         {
    //             key: 'uiComponent.common',
    //             path: '',
    //             title: 'Common',
    //             translateKey: 'nav.uiComponentsCommon.common',
    //             icon: 'common',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [ADMIN],
    //             subMenu: [
    //                 {
    //                     key: 'uiComponent.common.button',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/button`,
    //                     title: 'Button',
    //                     translateKey: 'nav.uiComponentsCommon.button',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.common.grid',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/grid`,
    //                     title: 'Grid',
    //                     translateKey: 'nav.uiComponentsCommon.grid',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.common.typography',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/typography`,
    //                     title: 'Typography',
    //                     translateKey: 'nav.uiComponentsCommon.typography',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.common.icons',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/icons`,
    //                     title: 'Icons',
    //                     translateKey: 'nav.uiComponentsCommon.icons',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //         {
    //             key: 'uiComponent.feedback',
    //             path: '',
    //             title: 'Feedback',
    //             translateKey: 'nav.uiComponentsFeeback.feedback',
    //             icon: 'feedback',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [ADMIN],
    //             subMenu: [
    //                 {
    //                     key: 'uiComponent.feedback.alert',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/alert`,
    //                     title: 'Alert',
    //                     translateKey: 'nav.uiComponentsFeeback.alert',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.feedback.dialog',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/dialog`,
    //                     title: 'Dialog',
    //                     translateKey: 'nav.uiComponentsFeeback.dialog',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.feedback.drawer',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/drawer`,
    //                     title: 'Drawer',
    //                     translateKey: 'nav.uiComponentsFeeback.drawer',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.feedback.progress',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/progress`,
    //                     title: 'Progress',
    //                     translateKey: 'nav.uiComponentsFeeback.progress',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.feedback.skeleton',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/skeleton`,
    //                     title: 'Skeleton',
    //                     translateKey: 'nav.uiComponentsFeeback.skeleton',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.feedback.spinner',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/spinner`,
    //                     title: 'Spinner',
    //                     translateKey: 'nav.uiComponentsFeeback.spinner',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.feedback.toast',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/toast`,
    //                     title: 'Toast',
    //                     translateKey: 'nav.uiComponentsFeeback.toast',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //         {
    //             key: 'uiComponent.dataDisplay',
    //             path: '',
    //             title: 'Data Display',
    //             translateKey: 'nav.uiComponentsDataDisplay.dataDisplay',
    //             icon: 'dataDisplay',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [ADMIN],
    //             subMenu: [
    //                 {
    //                     key: 'uiComponent.dataDisplay.avatar',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/avatar`,
    //                     title: 'Avatar',
    //                     translateKey: 'nav.uiComponentsDataDisplay.avatar',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.dataDisplay.badge',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/badge`,
    //                     title: 'Badge',
    //                     translateKey: 'nav.uiComponentsDataDisplay.badge',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.dataDisplay.calendar',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/calendar`,
    //                     title: 'Calendar',
    //                     translateKey: 'nav.uiComponentsDataDisplay.calendar',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.dataDisplay.cards',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/cards`,
    //                     title: 'Cards',
    //                     translateKey: 'nav.uiComponentsDataDisplay.cards',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.dataDisplay.table',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/table`,
    //                     title: 'Table',
    //                     translateKey: 'nav.uiComponentsDataDisplay.table',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.dataDisplay.tag',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/tag`,
    //                     title: 'Tag',
    //                     translateKey: 'nav.uiComponentsDataDisplay.tag',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //         {
    //             key: 'uiComponent.forms',
    //             path: '',
    //             title: 'Forms',
    //             translateKey: 'nav.uiComponentsForms.forms',
    //             icon: 'forms',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [ADMIN],
    //             subMenu: [
    //                 {
    //                     key: 'uiComponent.forms.checkbox',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/checkbox`,
    //                     title: 'Checkbox',
    //                     translateKey: 'nav.uiComponentsForms.checkbox',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.forms.datePicker',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/date-picker`,
    //                     title: 'Date picker',
    //                     translateKey: 'nav.uiComponentsForms.datePicker',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.forms.formControl',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/form-control`,
    //                     title: 'Form control',
    //                     translateKey: 'nav.uiComponentsForms.formControl',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.forms.input',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/input`,
    //                     title: 'Input',
    //                     translateKey: 'nav.uiComponentsForms.input',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.forms.inputGroup',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/input-group`,
    //                     title: 'Input Group',
    //                     translateKey: 'nav.uiComponentsForms.inputGroup',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.forms.radio',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/radio`,
    //                     title: 'Radio',
    //                     translateKey: 'nav.uiComponentsForms.radio',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.forms.select',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/select`,
    //                     title: 'Select',
    //                     translateKey: 'nav.uiComponentsForms.select',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.forms.switcher',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/switcher`,
    //                     title: 'Switcher',
    //                     translateKey: 'nav.uiComponentsForms.switcher',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.forms.timeInput',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/time-input`,
    //                     title: 'Time Input',
    //                     translateKey: 'nav.uiComponentsForms.timeInput',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.forms.upload',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/upload`,
    //                     title: 'Upload',
    //                     translateKey: 'nav.uiComponentsForms.upload',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //         {
    //             key: 'uiComponent.navigation',
    //             path: '',
    //             title: 'Navigation',
    //             translateKey: 'nav.uiComponentsNavigation.navigation',
    //             icon: 'navigation',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [ADMIN],
    //             subMenu: [
    //                 {
    //                     key: 'uiComponent.navigation.dropdown',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/dropdown`,
    //                     title: 'Dropdown',
    //                     translateKey: 'nav.uiComponentsNavigation.dropdown',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.navigation.menu',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/menu`,
    //                     title: 'Menu',
    //                     translateKey: 'nav.uiComponentsNavigation.menu',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.navigation.pagination',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/pagination`,
    //                     title: 'Pagination',
    //                     translateKey: 'nav.uiComponentsNavigation.pagination',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'uiComponent.navigation.tabs',
    //                     path: `${UI_COMPONENTS_PREFIX_PATH}/tabs`,
    //                     title: 'Tabs',
    //                     translateKey: 'nav.uiComponentsNavigation.tabs',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //             ],
    //         },
    //     ],
    // },
    // {
    //     parentKey:'Portals',
    //     key: 'portals',
    //     path: '',
    //     title: 'Portals',
    //     translateKey: '',
    //     icon: 'apps',
    //     type: NAV_ITEM_TYPE_TITLE,
    //     authority: [ADMIN],
    //     subMenu: [
    //         // {
    //         //     key: 'apps.project',
    //         //     path: '',
    //         //     title: 'Project',
    //         //     translateKey: 'nav.appsProject.project',
    //         //     icon: 'project',
    //         //     type: NAV_ITEM_TYPE_COLLAPSE,
    //         //     authority: [ADMIN],
    //         //     subMenu: [
    //         //         {
    //         //             key: 'appsProject.dashboard',
    //         //             path: `${APP_PREFIX_PATH}/project/dashboard`,
    //         //             title: 'Dashboard',
    //         //             translateKey: 'nav.appsProject.dashboard',
    //         //             icon: '',
    //         //             type: NAV_ITEM_TYPE_ITEM,
    //         //             authority: [ADMIN],
    //         //             subMenu: [],
    //         //         },
    //         //         {
    //         //             key: 'appsProject.projectList',
    //         //             path: `${APP_PREFIX_PATH}/project/project-list`,
    //         //             title: 'Project List',
    //         //             translateKey: 'nav.appsProject.projectList',
    //         //             icon: '',
    //         //             type: NAV_ITEM_TYPE_ITEM,
    //         //             authority: [ADMIN],
    //         //             subMenu: [],
    //         //         },
    //         //         {
    //         //             key: 'appsProject.scrumBoard',
    //         //             path: `${APP_PREFIX_PATH}/project/scrum-board`,
    //         //             title: 'Scrum Board',
    //         //             translateKey: 'nav.appsProject.scrumBoard',
    //         //             icon: '',
    //         //             type: NAV_ITEM_TYPE_ITEM,
    //         //             authority: [ADMIN],
    //         //             subMenu: [],
    //         //         },
    //         //         {
    //         //             key: 'appsProject.issue',
    //         //             path: `${APP_PREFIX_PATH}/project/issue`,
    //         //             title: 'Issue',
    //         //             translateKey: 'nav.appsProject.issue',
    //         //             icon: '',
    //         //             type: NAV_ITEM_TYPE_ITEM,
    //         //             authority: [ADMIN],
    //         //             subMenu: [],
    //         //         },
    //         //     ],
    //         // },
         
    //         {
    //             key: 'apps.app',
    //             path: '',
    //             title: 'Events',
    //             translateKey: 'nav.appsCrm.app',
    //             icon: 'crm',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [ADMIN],
    //             subMenu: [
    //                 // {
    //                 //     key: 'appsApp.dashboard',
    //                 //     path: `${APP_PREFIX_PATH}/crm/dashboard`,
    //                 //     title: 'Dashboard',
    //                 //     translateKey: 'nav.appsCrm.dashboard',
    //                 //     icon: '',
    //                 //     type: NAV_ITEM_TYPE_ITEM,
    //                 //     authority: [ADMIN],
    //                 //     subMenu: [],
    //                 // },
                   

            
    //                 {

    //                     key: 'appsApp.sports',
    //                     path: `${APP_PREFIX_PATH}/apps/poolevents`,
    //                     title: 'Sports',
    //                     translateKey: 'nav.apps.sports',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_COLLAPSE,
    //                     authority: [ADMIN],
    //                     subMenu: [
    //                         {
    //                             key: 'appsApp.sports.poolevents',
    //                             path: `${APP_PREFIX_PATH}/apps/poolevents`,
    //                             title: 'Pool Events',
    //                             translateKey: 'nav.apps.poolevents',
    //                             icon: '',
    //                             type: NAV_ITEM_TYPE_ITEM,
    //                             authority: [ADMIN],
    //                             subMenu: [],
    //                         }
    //                     ],
    //                 },

    //                 {
    //                     key: 'appsApp.poolgames',
    //                     path: `${APP_PREFIX_PATH}/apps/poolgames`,
    //                     title: 'Pool Games',
    //                     translateKey: 'nav.apps.poolgames',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },


    //             ],
    //         },
    //         // {
    //         //     key: 'appsApp.pool',
    //         //     path: `${APP_PREFIX_PATH}/apps/pool`,
    //         //     title: 'Pools',
    //         //     translateKey: 'nav.apps.pool',
    //         //     icon: 'crm',
    //         //     type: NAV_ITEM_TYPE_COLLAPSE,
    //         //     authority: [ADMIN],
    //         //     subMenu: [
    //         //         {
    //         //             key: 'appsApp.pool',
    //         //             path: `${APP_PREFIX_PATH}/apps/pool`,
    //         //             title: 'Pools List',
    //         //             translateKey: 'nav.apps.pool',
    //         //             icon: '',
    //         //             type: NAV_ITEM_TYPE_COLLAPSE,
    //         //             authority: [ADMIN],
    //         //             subMenu: [],
    //         //         },
    //         //         // {
    //         //         //     key: 'appsApp.poolEntries',
    //         //         //     path: `${APP_PREFIX_PATH}/apps/poolEntries`,
    //         //         //     title: 'Pool Entries',
    //         //         //     translateKey: 'nav.apps.poolEntries',
    //         //         //     icon: '',
    //         //         //     type: NAV_ITEM_TYPE_COLLAPSE,
    //         //         //     authority: [ADMIN],
    //         //         //     subMenu: [],
    //         //         // },
    //         //         // {
    //         //         //     key: 'appsApp.poolMembers',
    //         //         //     path: `${APP_PREFIX_PATH}/apps/poolMembers`,
    //         //         //     title: 'Pool Members',
    //         //         //     translateKey: 'nav.apps.poolEntries',
    //         //         //     icon: '',
    //         //         //     type: NAV_ITEM_TYPE_COLLAPSE,
    //         //         //     authority: [ADMIN],
    //         //         //     subMenu: [],
    //         //         // },
    //         //         // {
    //         //         //     key: 'appsApp.poolRequests',
    //         //         //     path: `${APP_PREFIX_PATH}/apps/poolRequests`,
    //         //         //     title: 'Pool Requests',
    //         //         //     translateKey: 'nav.apps.poolRequests',
    //         //         //     icon: '',
    //         //         //     type: NAV_ITEM_TYPE_COLLAPSE,
    //         //         //     authority: [ADMIN],
    //         //         //     subMenu: [],
    //         //         // }
                    
    //         //     ],
    //         // },
    //         {
    //             key: 'apps.cms',
    //             path: '',
    //             title: 'CMS',
    //             translateKey: 'nav.appsCms.app',
    //             icon: 'crm',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [ADMIN],
    //             subMenu: [
    //                 // {
    //                 //     key: 'appsApp.dashboard',
    //                 //     path: `${APP_PREFIX_PATH}/crm/dashboard`,
    //                 //     title: 'Dashboard',
    //                 //     translateKey: 'nav.appsCrm.dashboard',
    //                 //     icon: '',
    //                 //     type: NAV_ITEM_TYPE_ITEM,
    //                 //     authority: [ADMIN],
    //                 //     subMenu: [],
    //                 // },

                    

    //                 {
    //                     key: 'appsCms.faqs',
    //                     path: `${APP_PREFIX_PATH}/cms/faqs`,
    //                     title: 'Faqs',
    //                     translateKey: 'nav.appsCms.faqs',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'appsCms.page',
    //                     path: `${APP_PREFIX_PATH}/cms/page`,
    //                     title: 'Page',
    //                     translateKey: 'nav.appsCms.page',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },

    //             ],
    //         },
          
    //         {
    //             key: 'apps.support',
    //             path: '',
    //             title: 'Support',
    //             translateKey: 'nav.appsupport.app',
    //             icon: 'feedback',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [ADMIN],
    //             subMenu: [
    //                 {
    //                     key: 'appsSupport.notifications',
    //                     path: `${APP_PREFIX_PATH}/support/notifications`,
    //                     title: 'Notifications',
    //                     translateKey: 'nav.appsSupport.notifications',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
    //                 {
    //                     key: 'appsSupport.inquiries',
    //                     path: `${APP_PREFIX_PATH}/support/inquiries`,
    //                     title: 'Inquiries',
    //                     translateKey: 'nav.appsSupport.inquiries',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },



    //             ],
    //         },
    //         {
    //             key: 'apps.maintenance',
    //             path: '',
    //             title: 'Maintenance',
    //             translateKey: 'nav.appmaintenance.app',
    //             icon: 'feedback',
    //             type: NAV_ITEM_TYPE_COLLAPSE,
    //             authority: [ADMIN],
    //             subMenu: [
    //                 {
    //                     key: 'appsMaintenance.alert',
    //                     path: `${APP_PREFIX_PATH}/maintenance/alert`,
    //                     title: 'Alert Setting',
    //                     translateKey: 'nav.appsMaintenance.alert',
    //                     icon: '',
    //                     type: NAV_ITEM_TYPE_ITEM,
    //                     authority: [ADMIN],
    //                     subMenu: [],
    //                 },
               


    //             ],
    //         },
       
    //     ],
    // }
]

export default uiComponentNavigationConfig
